name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Caching dependencies
        uses: actions/cache@v1
        with:
          path: '~/.yarn'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Installing dependencies
        run: yarn

      - name: Building
        run: yarn build
