name: CI

on:
  push:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Caching node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - name: Installing dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.7.6
          run_install: |
            - args: [--frozen-lockfile]

      - name: Linting
        run: pnpm run validate

      - name: Building
        run: pnpm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: public

  deploy:
    runs-on: ubuntu-latest

    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Deploying to github-pages
        run: |
          git init
          git config user.name "vigenere23"
          git config user.email "32545895+vigenere23@users.noreply.github.com"
          git add -A
          git commit -m 'deploy'
          git push -f https://x-access-token:${{ secrets.GITHUBIO_DEPLOY }}@github.com/vigenere23/vigenere23.github.io master
