name: CI

on:
  push:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.13.0
          cache: pnpm

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm run validate

      - name: Building
        run: pnpm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: public

  deploy:
    runs-on: ubuntu-latest

    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Deploying to github-pages
        run: |
          git init
          git config user.name "vigenere23"
          git config user.email "32545895+vigenere23@users.noreply.github.com"
          git add -A
          git commit -m 'deploy'
          git push -f https://x-access-token:${{ secrets.GITHUBIO_DEPLOY }}@github.com/vigenere23/vigenere23.github.io master
