name: Github pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Caching dependencies
        uses: actions/cache@v1
        with:
          path: '~/.yarn'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Installing dependencies
        run: yarn

      - name: Linting
        run: yarn validate

      - name: Building for production
        run: yarn build

      - name: Deploying to github-pages
        run: |
          cd public
          git init
          git config user.name "vigenere23"
          git config user.email "32545895+vigenere23@users.noreply.github.com"
          git add -A
          git commit -m 'deploy'
          git push -f https://x-access-token:${{ secrets.GITHUBIO_DEPLOY }}@github.com/vigenere23/vigenere23.github.io master
